### ISSUE TITLE
Serverless Function for Attendance Registration

### ISSUE THREAD

**Issue by steffen74** [eduhub-org/eduhub#63]
It must be checked how the frontend is currently querying and displaying the data.
Changes by the course instructors are probably not saved correct at the moment (i.e. as additional rows in the attendance table).
The whole process must be reviewed again and the frontend be changed correspondingly.

### Details
- ...

### Optional and Future Implementations
- NA

**Comment by freerafiki** [comment]
I was thinking about the workflow for the attendance registration. 
The main issue is how to handle multiple sources (zoom, other platform, manual inserts) and multiple information about the same person (update, insert a new one and check the most recent) because as the table grows, looking for the most recent occurrence of a certain person may start to get tricky.

My first idea is the following:

### 1. Cron Trigger on each `Session` of each `Course`
As soon as a new `Course` is added to the platform, some `Session` will be added (a `Course` must have at least one, see #51 for details). For each of this session, we have a `Start` and a `Finish` value. 
I would set a Cron Trigger after the `Finish` value (maybe 1 hour later to be sure), which reads the `Enrollment` table, checks the enrollments relative to the `Course` we are in (`Enrollment.CourseId == Session.CourseId`) and writes in the `Attendance` table all the participants with `Status = False` (now it's Attending, but it should be changed, as in #49 ).
**_This way we are sure that all participants are already present in the `Attendence` table and their `created_at` value will be corresponding to the `Session` 's `Finish` value, so that they are easy to be found even later_**.
The hope is that the trigger can be automatically set as soon as a new `Session` is inserted (probably this could also be an event trigger on the `Session` table)

### 2. Event Trigger on the `Attendance` Table
This is a general trigger that would work for all the courses, so we can add it manually. We would most likely need some logic here. When there is a "bulk insert" (not a single changes, but a changes with more affected rows) in the `Attendance` table (this is needed to avoid triggering this when manual changes happens, for example admin or course instructors changing attendances for a single person), a call to the serverless function for Zoom will be made, passing as parameters the "affected rows" (this would be the participants). This would save the serverless function from having to look for the entries in the database, which can be a good option when it gets bigger.
_However, in theory, if we would need to search these values, we could filter out the `Attendance` table by keeping only the entries with `created_at` in a certain range (`Session.Finish` to `Session.Finish` + 2/3 hours) and these should be a relatively small amount._
I am still thinking whether this may be problematic in case we have other sources of attendances (for example other online platform or videoconferencing tools), because they would also update the `Attendance` table, but they would not insert. As long as the `insert` is made only from the cron trigger described above, this should be safe. We could just add the in this event trigger a call to the other platform (not only Zoom) if we would use more in the future.

### 3. Serverless function updates `Attendance` Table
The serverless function than always receives some data to work on. It should be the participants of the course. Some checks should be performed (maybe that time and course id are correct) and if they fail, we can send a mail to us "admins". Then it can start fetching from Zoom the participants, and match them with the ones from the list. For all of the participants where the match happened (still same problem as last semesters with the matching), the function will call an hasura mutation to _update_ (not insert) the participants (updating for example `Attending`, `TypeRegistration`, `NameRegistered`, `TimeStart`, `TimeEnd`, `NumberInterruptions`). This will be saved in the `Attendance` table in the `updated_at` column, so it is kept track of. 
In the case where the names matched are less than a certain threshold (maybe a percentage of the whole participants), we can add a mail to the course instructor explaining that no attendances have been found in Zoom and if s/he did this in presence or with other tools, s/he should manually check the attendances.

I will try to think it through and check feasibility before implementing it.

**Comment by freerafiki** [comment]
After discussing with Steffen, we can try to simplify this by reducing triggers and calls. 

The serverless function should check the attendance not only from Zoom, but also from other sources, at least from Limesurvey (for offline registration). 

Updates:

- The serverless function needs permission to read/write to hasura, easier way with the secret, not sure if there is a more "secure" way. 
- The serverless function can be called directly after each session and will do several steps: a) will ask hasura to get the list of registered participants, b) will ask zoom to get the protocol (online participants), c) will ask limesurvey to get the survey results (offline participants) d) will match registered against online and offline participants, e) will write in the `Attendance` table the matched one as present, the unmatched one as missing and the one who participated but were not registered to the course also as present.

If later we may need to fetch attendances from other platform (apart from Zoom and Limesurvey) we can just add after step c) and before step d)
