### ISSUE TITLE
[BUG] Plain Window 11 - successfully cloned repo but failed checkout due to invalid path

### ISSUE THREAD

**Issue by hpk0304** [eduhub-org/eduhub#817]
**Describe the bug**
The clone process succeeded but failed checkout due to invalid path in backend. 

It might be an issue of operating system: A filename `uuid/down.sql` might work well on Linux instead of Window.

**Expected behavior**
Shall you rename the file, with suggestion from Stackoverflow here https://stackoverflow.com/questions/61614004/cloning-succeded-but-checkout-failed-due-to-invalid-path-what-is-the-path-probl

**Screenshots**
![bug](https://github.com/eduhub-org/eduhub/assets/13078617/04cb47d8-a569-48f4-a16f-32e12caf8095)

**Environment (please complete the following information):**
 - Window 11
 - Browser Bing

**Additional context**

**Comment by mattinannt** [comment]
<img width="656" alt="Screenshot 2023-11-17 at 14 41 11" src="https://github.com/eduhub-org/eduhub/assets/675065/6ded5c97-b2b9-4ad3-83d6-62c9f9328c13">

It seems the filename containing spaces and or special characters like `>` leads to these errors. Is it possible to rename the folder without killing the migrations? @ericstumper

**Comment by steffen74** [comment]
@mattinannt Yes, it is possible. However, it is not straightforward since renaming changes the status of the migration indicating that Hasura should execute it again. Therefore it is important to mark it as executed again right after renaming it.
The steps are the following ones:

1. Stop Hasura if it's running.
1. Navigate to the migrations directory in your Hasura project.
1. Find the migration folder you want to rename. Migration folders are named with a timestamp followed by the migration name.
1. Rename the folder. Make sure to keep the timestamp the same and only change the name part! This is important because Hasura applies migrations in the order of the timestamp, and the timestamp is also the version number of the migration.
1. Execute the following command: `hasura migrate apply --version <version> --skip-execution`
Replace `<version>` with the version number (i.e., the timestamp) of the migration.
1. Start Hasura and apply the migrations.

Generally I would follow what you said @mattinannt, that it makes more sense to only support Codespaces and Gitpod since particularly with Windows there are a lot of issues.
